= Designed Problem — The Siege

== Problem description

You are Warchief Grukk, commanding an assault on $N$ dwarven strongholds. Each stronghold is a network of one-way mine shafts: carts can only travel in one direction through each tunnel (the network is a directed graph). Deep inside each stronghold is the Gold Vein (room $0$, the source); the entrance where wolf-riders wait is room $V_i - 1$ (the sink). Each tunnel has a weight limit (capacity) giving the maximum kilograms of gold carts can carry through it per hour. Your miners extract gold at the maximum possible rate — the max-flow of the network.

Each stronghold costs $c_i$ orc warriors to conquer. You have $B$ warriors total. Choose which strongholds to conquer to maximise total gold extracted.

*Input.* First line: integers $N$ and $B$ $(1 <= N <= 50, 1 <= B <= 1000)$. Then $N$ stronghold descriptions, each starting with: name $s_i$ (lowercase, length $<= 20$), cost $c_i$ $(1 <= c_i <= B)$, rooms $V_i$ $(2 <= V_i <= 15)$, edges $E_i$ $(1 <= E_i <= 40)$. Followed by $E_i$ lines each giving $u$, $v$, $w$ for a directed tunnel from room $u$ to $v$ with capacity $w$ $(1 <= w <= 100)$.

*Output.* One line per selected stronghold, format `<index> <name>`, in ascending index order. The optimal subset is guaranteed unique.

*Sample input 1:*
```
3 10
ironkeep 3 3 2
0 1 5
1 2 2
stonewall 6 4 4
0 1 3
0 2 2
1 3 2
2 3 3
thornhold 4 3 2
0 1 4
1 2 3
```

*Sample output 1:*
```
1 stonewall
2 thornhold
```

Max-flows: ironkeep = 2 (bottleneck edge 1→2, cap 2), stonewall = 4 (two augmenting paths: 0→1→3 flow 2, then 0→2→3 flow 2), thornhold = 3. With $B = 10$: stonewall+thornhold costs $6+4=10 <= 10$, gold $4+3=7$. ironkeep+stonewall costs $9$, gold $2+4=6$. So optimal is stonewall+thornhold.

== Intended solution

The problem decomposes into two independent subproblems applied sequentially:

1. *Per-stronghold max-flow.* For each stronghold $i$, compute the maximum flow from room $0$ to room $V_i - 1$ using Edmonds-Karp (BFS-augmented Ford-Fulkerson). This gives the gold value $g_i$.

2. *0/1 Knapsack DP.* Treat each stronghold as a knapsack item with weight $c_i$ and value $g_i$. Find the subset of items with total weight $<= B$ that maximises total value.

```
function solve():
    for each stronghold i:
        g[i] = edmonds_karp(graph_i, source=0, sink=V_i - 1)

    dp[0..N][0..B] = 0               // dp[i][j] = best gold using first i strongholds, budget j
    for i in 1..N:
        for j in 0..B:
            dp[i][j] = dp[i-1][j]    // skip stronghold i
            if j >= c[i]:
                dp[i][j] = max(dp[i][j], g[i] + dp[i-1][j - c[i]])

    // backtrack to recover selected indices
    remaining = B
    for i from N down to 1:
        if dp[i][remaining] != dp[i-1][remaining]:
            select stronghold i-1
            remaining -= c[i-1]
    output selected in ascending order
```

*Time complexity:*
- Edmonds-Karp per stronghold: $O(V_i dot.c E_i^2)$. With $V_i <= 15$, $E_i <= 40$: at most $15 times 40^2 = 24000$ operations each.
- All $N$ max-flows: $O(N dot.c V_(max) dot.c E_(max)^2) approx 50 times 24000 = 1.2 times 10^6$.
- Knapsack DP: $O(N dot.c B) = 50 times 1000 = 50000$.
- *Overall:* $O(N dot.c V E^2 + N B)$ — effectively constant given the small bounds.

*Memory:* $O(V_(max)^2)$ for the adjacency matrix per flow computation, $O(N dot.c B)$ for the DP table.

== Test-case design

*Sample tests* (manually crafted, small enough for hand-verification):

- *1-small-manual:* 3 strongholds, $B=10$. Tests basic knapsack selection; greedy by ratio picks the wrong pair.
- *2-medium-manual:* 3 strongholds with parallel-path graphs. Verifies that multi-path flow is summed correctly.
- *3-single-manual:* $N=1$, tests single-stronghold boundary; the one stronghold is within budget so it is selected.
- *4-zeroflow-manual:* One stronghold has no $s$-$t$ path (disconnected graph, flow = 0). Tests that a zero-gold stronghold is correctly skipped when a positive-gold alternative exists within budget.

*Secret tests* (generated by `generators/generator.py` or hand-crafted for specific corner cases):

- *1-single:* $N=1$, $B$ large — single item always selected if affordable.
- *2-small:* $N <= 5$, $B <= 20$ — brute-force can verify correctness.
- *3-medium:* $N approx 20$, $B approx 200$ — exercises DP without hitting any limit.
- *4-large:* $N=50$, $B=1000$ — maximum constraint stress test; brute-force $2^(50)$ is impossible.
- *5-tiebreak:* Constructed so two subsets tie in gold before one is broken by careful cost arrangement; validator enforces uniqueness, so this test confirms no two optimal subsets exist.
- *6-zeroflow:* Multiple strongholds with disconnected graphs (no $s$-$t$ path, gold = 0); tests that zero-value items do not inflate the knapsack answer.
- *7-cycle:* Graphs containing cycles and back-edges; confirms that residual graph reverse-edge handling in Edmonds-Karp is correct (a bug here would under-count flow).

*Corner cases covered:* $N=1$; $B$ exactly equal to one item cost; all items affordable; no item affordable; zero flow; graphs that are chains, parallel paths, or contain cycles.

== Accepted and wrong solutions

*Accepted — `submissions/accepted/solution.py` (Python 3) and `solution.rs` (Rust):*
Edmonds-Karp max-flow per stronghold, then 0/1 knapsack DP with backtracking. Both produce identical output. The Python solution runs comfortably within 2 seconds given the small problem bounds; the Rust solution is included as a fast reference.

*TLE — `submissions/time_limit_exceeded/brute_force.py` / `brute_force.rs`:*
Enumerates all $2^N$ subsets, computes total cost and gold for each, and keeps the best feasible subset. Correct for small $N$ but $2^(50) approx 10^(15)$ iterations makes it infeasible for $N = 50$. Used to verify correctness of the DP solution on small inputs.

*WA — `submissions/wrong_answer/greedy.py`:*
Sorts strongholds by the gold-per-warrior ratio $g_i / c_i$ descending and greedily adds items as long as they fit in the remaining budget. This is the optimal strategy for *fractional* knapsack but fails for 0/1 knapsack. Counter-example from sample 1: ratios are stonewall $approx 0.67$, thornhold $0.75$, ironkeep $approx 0.67$. Greedy picks thornhold ($c=4$, $g=3$) then ironkeep ($c=3$, $g=2$), total cost $7$, gold $5$. Optimal is stonewall + thornhold ($c=10$, $g=7$).

== Input validation & formatting

`input_validators/validator.py` enforces all constraints via regex and range checks, then runs a full knapsack over all test inputs to confirm the optimal solution is *unique* (exits with code 43 if $>= 2$ optimal subsets exist, exits with code 42 on success). Specific checks:

- Line 1 matches `^[1-9][0-9]* [1-9][0-9]*\n$`; $N in [1,50]$, $B in [1,1000]$.
- Each castle header: name lowercase letters only, length $<= 20$, globally unique; $c_i in [1, B]$; $V_i in [2, 15]$; $E_i in [1, 40]$.
- Each edge line: $u, v in [0, V_i - 1]$, $u != v$, no duplicate $(u, v)$ pair within the same stronghold; $w in [1, 100]$.
- No trailing content after the last edge.

Contestants may assume all input is well-formed and within these bounds.

== Verify notes

`verifyproblem` was run from the `problem/thesiege/` directory. All sample and secret test cases pass the validator (exit 42). The accepted solutions pass all tests. The brute-force solution is correctly flagged TLE on `4-large` and the greedy is correctly flagged WA on `1-small-manual`. No warnings were produced.

== Testing and Validation

Run the accepted Python solution on a sample test:

```bash
python3 submissions/accepted/solution.py < data/sample/1-small-manual.in
```

Run the validator on an input (exit code 42 = valid and unique-optimal, 43 = invalid):

```bash
python3 input_validators/validator.py < data/sample/1-small-manual.in; echo "exit $?"
```

Generate a large random test and time the accepted solution:

```bash
python3 generators/generator.py 42 50 1000 15 40 100 > /tmp/large.in
time python3 submissions/accepted/solution.py < /tmp/large.in
```

Diff DP against brute-force on a small instance:

```bash
python3 generators/generator.py 7 5 20 8 15 50 > /tmp/small.in
python3 submissions/accepted/solution.py < /tmp/small.in > /tmp/dp.out
python3 submissions/time_limit_exceeded/brute_force.py < /tmp/small.in > /tmp/bf.out
diff /tmp/dp.out /tmp/bf.out
```

== Source for Designed Problem

Repository layout under `problem/thesiege/`:

```
problem/thesiege/
  problem.yaml                       problem metadata (name, type, uuid)
  problem_statement/problem.en.tex   LaTeX problem statement
  submissions/
    accepted/solution.py             Python 3 accepted solution
    accepted/solution.rs             Rust accepted solution
    time_limit_exceeded/brute_force.py
    time_limit_exceeded/brute_force.rs
    wrong_answer/greedy.py
  generators/generator.py            parametric random generator
  input_validators/validator.py      constraint + uniqueness checker
  data/
    sample/   4 hand-crafted sample cases (.in / .ans)
    secret/   7 generated/hand-crafted secret cases (.in / .ans)
```

Run locally with `verifyproblem` (requires the `problemtools` package):

```bash
cd problem/
verifyproblem thesiege/
```
